// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
#[derive(::std::fmt::Debug, ::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct Args {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<::std::string::String>,
    #[serde(rename = "reasonType")]
    pub reason_type: _lex::com::atproto::moderation::defs::ReasonType,
    pub subject: (),
}

#[derive(::std::fmt::Debug, ::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct Responce {
    #[serde(rename = "createdAt")]
    pub created_at: _lex::_rt::Datetime,
    pub id: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<::std::string::String>,
    #[serde(rename = "reasonType")]
    pub reason_type: _lex::com::atproto::moderation::defs::ReasonType,
    #[serde(rename = "reportedBy")]
    pub reported_by: _lex::_rt::Did,
    pub subject: (),
}
