// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
///Misleading identity, affiliation, or content
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonMisleading;

///Other: reports not falling under another report category
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonOther;

///Rude, harassing, explicit, or otherwise unwelcoming behavior
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonRude;

///Unwanted or mislabeled sexual content
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonSexual;

///Spam: frequent unwanted promotion, replies, mentions
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonSpam;

#[derive(
    ::std::fmt::Debug,
    ::std::clone::Clone,
    ::serde::Deserialize,
    ::serde::Serialize,
    ::libipld::DagCbor,
)]
pub struct ReasonType(::std::string::String);

///Direct violation of server rules, laws, terms of service
#[derive(::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct ReasonViolation;
