[package]
name = "triphosphate"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/aDotInTheVoid/triphosphate"
description = "WIP ATProto SKD"

[workspace]
members = [
    "lexgen"
]

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
