// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
pub struct Params {
    pub actor: _lex::_rt::AtIdentifier,
}
impl _lex::_rt::AsParams for Params {
    fn as_params(&self) -> Vec<(&'static str, String)> {
        let mut r: Vec<(&'static str, String)> = Vec::with_capacity(1usize);
        {
            let actor = &self.actor;
            r.push(("actor", _lex::_rt::StringFormat::as_str(actor).to_owned()));
        }
        r
    }
}
