// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod app;
pub mod com;

mod _lex {
    pub(crate) use super::super::vocab as _rt;
    pub(crate) use super::app;
    pub(crate) use super::com;
}
