// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
#[derive(:: std :: clone :: Clone, :: serde :: Deserialize, :: serde :: Serialize)]
pub struct External {
    pub description: ::std::string::String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumb: Option<_lex::_rt::Blob>,
    pub title: ::std::string::String,
    pub uri: _lex::_rt::Uri,
}
impl _lex::_rt::LexItem for External {
    const URI: &'static str = "app.bsky.embed.external#external";
}
#[derive(:: std :: clone :: Clone, :: serde :: Deserialize, :: serde :: Serialize)]
pub struct View {
    pub external: _lex::app::bsky::embed::external::ViewExternal,
}
impl _lex::_rt::LexItem for View {
    const URI: &'static str = "app.bsky.embed.external#view";
}
#[derive(:: std :: clone :: Clone, :: serde :: Deserialize, :: serde :: Serialize)]
pub struct ViewExternal {
    pub description: ::std::string::String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumb: Option<::std::string::String>,
    pub title: ::std::string::String,
    pub uri: _lex::_rt::Uri,
}
impl _lex::_rt::LexItem for ViewExternal {
    const URI: &'static str = "app.bsky.embed.external#viewExternal";
}
