// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
#[derive(
    ::std::fmt::Debug,
    ::std::clone::Clone,
    ::std::cmp::PartialEq,
    ::serde::Deserialize,
    ::serde::Serialize,
    ::libipld::DagCbor,
)]
pub struct Image {
    pub alt: ::std::string::String,
    pub image: _lex::_rt::Blob,
}
impl _lex::_rt::LexItem for Image {
    const URI: &'static str = "app.bsky.embed.images#image";
}

#[derive(
    ::std::fmt::Debug,
    ::std::clone::Clone,
    ::std::cmp::PartialEq,
    ::serde::Deserialize,
    ::serde::Serialize,
    ::libipld::DagCbor,
)]
pub struct View {
    pub images: Vec<_lex::app::bsky::embed::images::ViewImage>,
}
impl _lex::_rt::LexItem for View {
    const URI: &'static str = "app.bsky.embed.images#view";
}

#[derive(
    ::std::fmt::Debug,
    ::std::clone::Clone,
    ::std::cmp::PartialEq,
    ::serde::Deserialize,
    ::serde::Serialize,
    ::libipld::DagCbor,
)]
pub struct ViewImage {
    pub alt: ::std::string::String,
    pub fullsize: ::std::string::String,
    pub thumb: ::std::string::String,
}
impl _lex::_rt::LexItem for ViewImage {
    const URI: &'static str = "app.bsky.embed.images#viewImage";
}
