// Code generated by triphosphate lexgen. DO NOT EDIT.

#[allow(unused_imports)]
use super::super::super::super::_lex;
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct Image {
    pub alt: ::std::string::String,
    pub image: _lex::_rt::Blob,
}
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct View {
    pub images: (),
}
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct ViewImage {
    pub alt: ::std::string::String,
    pub fullsize: ::std::string::String,
    pub thumb: ::std::string::String,
}
