// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod defs;
pub mod get_profile;

#[allow(unused_imports)]
use super::super::super::_lex;
pub async fn get_profile(
    client: &_lex::_rt::Client,
    args: &_lex::app::bsky::actor::get_profile::Params,
) -> _lex::_rt::Result<_lex::app::bsky::actor::defs::ProfileViewDetailed> {
    client.do_query("app.bsky.actor.getProfile", args).await
}
