// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod external;
pub mod images;
pub mod record;
pub mod record_with_media;

#[allow(unused_imports)]
use super::super::super::_lex;
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct External {
    pub external: _lex::app::bsky::embed::external::External,
}
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct Images {
    pub images: (),
}
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct Record {
    pub record: _lex::com::atproto::repo::StrongRef,
}
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct RecordWithMedia {
    pub media: (),
    pub record: _lex::app::bsky::embed::Record,
}
