// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod post;

#[allow(unused_imports)]
use super::super::super::_lex;
#[derive(:: serde :: Deserialize, :: serde :: Serialize)]
pub struct Post {
    #[serde(rename = "createdAt")]
    pub created_at: (),
    pub embed: Option<()>,
    #[doc = "Deprecated: replaced by app.bsky.richtext.facet."]
    pub entities: Option<()>,
    pub facets: Option<()>,
    pub langs: Option<()>,
    pub reply: Option<_lex::app::bsky::feed::post::ReplyRef>,
    pub text: (),
}
