// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod get_unread_count;

#[allow(unused_imports)]
use super::super::super::_lex;
pub async fn get_unread_count(
    client: &_lex::_rt::Client,
    args: &_lex::app::bsky::notification::get_unread_count::Params,
) -> _lex::_rt::Result<_lex::app::bsky::notification::get_unread_count::Responce> {
    client
        .do_query("app.bsky.notification.getUnreadCount", args)
        .await
}
