// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod facet;

#[allow(unused_imports)]
use super::super::super::_lex;
#[derive(::std::fmt::Debug, ::std::clone::Clone, ::serde::Deserialize, ::serde::Serialize)]
pub struct Facet {
    pub features: Vec<()>,
    pub index: _lex::app::bsky::richtext::facet::ByteSlice,
}
impl _lex::_rt::LexItem for Facet {
    const URI: &'static str = "app.bsky.richtext.facet";
}
