// Code generated by triphosphate lexgen. DO NOT EDIT.

#[doc = "Deprecated: use facets instead."]
pub struct Entity;
pub struct ReplyRef;
#[doc = "Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings."]
pub struct TextSlice;
