name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/setup-node@v3
      with:  
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: lexgen/package-lock.json
    - run: cd lexgen && npm ci
    - run: cd lexgen && ./build_validator.sh
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --all
    - run: cargo test --all