// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod resolve_handle;

#[allow(unused_imports)]
use super::super::super::_lex;
///Provides the DID of a repo.
pub async fn resolve_handle(
    client: &_lex::_rt::Client,
    args: &_lex::com::atproto::identity::resolve_handle::Params,
) -> _lex::_rt::Result<_lex::com::atproto::identity::resolve_handle::Responce> {
    client
        .do_query("com.atproto.identity.resolveHandle", args)
        .await
}
