// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod create_report;
pub mod defs;

#[allow(unused_imports)]
use super::super::super::_lex;
///Report a repo or a record.
pub async fn create_report(
    client: &_lex::_rt::Client,
    args: &_lex::com::atproto::moderation::create_report::Args,
) -> _lex::_rt::Result<_lex::com::atproto::moderation::create_report::Responce> {
    client
        .do_procedure("com.atproto.moderation.createReport", args)
        .await
}
