// Code generated by triphosphate lexgen. DO NOT EDIT.
pub mod create_session;

#[allow(unused_imports)]
use super::super::super::_lex;
///Create an authentication session.
pub async fn create_session(
    client: &_lex::_rt::Client,
    args: &_lex::com::atproto::server::create_session::Args,
) -> ::reqwest::Result<_lex::com::atproto::server::create_session::Responce> {
    client
        .do_procedure("com.atproto.server.createSession", args)
        .await
}
